[package]
name = "ams2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
sdl2 = "0.35"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
bus = "2.2"
